### ISSUE TITLE
Remove "Django-" from Django-north

### ISSUE THREAD

**Issue by lisael** [peopledoc/django-north#21]
Migration is not a django-only issue. Every project that rely on postgresql need a way to manage migrations.

I think Django-north core is not tightly bound to Django and could be distributed as a framework-agnostic lib, and provide  a thin django layer as a subpackage, like so:

```
north/
|- __init__.py
|- core/
|  `- __init__.py
|- django/
|  |- __init__.py
|  `- management/
|- flask/
|  `- __init__.py
`- whatever_you_get_the_point/
   `- __init__.py
```

**Comment by ewjoachim** [comment]
(but the pun with Django South would be completely lost 😮 )

**Comment by zebuline** [comment]
In progress with https://github.com/peopledoc/west

**Comment by ewjoachim** [comment]
@lisael was a visionary :)
